package ca.ucalgary.codesets.controllers;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import org.eclipse.debug.core.DebugEvent;
import org.eclipse.debug.core.DebugPlugin;
import org.eclipse.debug.core.IDebugEventSetListener;
import org.eclipse.jdt.core.ISourceReference;
import org.eclipse.jface.action.IToolBarManager;
import org.eclipse.swt.SWT;
import org.eclipse.swt.layout.RowLayout;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Label;
import org.eclipse.ui.ISharedImages;
import org.eclipse.ui.PlatformUI;
import org.eclipse.ui.forms.events.HyperlinkEvent;
import org.eclipse.ui.forms.events.IHyperlinkListener;

import ca.ucalgary.codesets.models.CodeSet;
import ca.ucalgary.codesets.models.CodeSetManager;
import ca.ucalgary.codesets.models.ICodeSetListener;
import ca.ucalgary.codesets.models.TextBox;
import ca.ucalgary.codesets.views.CodeSetLabel;
import ca.ucalgary.codesets.views.SideBarSection;

//a controller for the "side bar" view that allows users to specify the combination
//of events that they are interested in
public class SideBarController implements ICodeSetListener {
	// the ui is a simple series of SideBarSections
	
	HashMap<String, SideBarSection> sections = new HashMap<String, SideBarSection>();
	Composite sideBar;
	IToolBarManager toolBarManager;

	public SideBarController(Composite parent) {
		sideBar = view(parent);		
		addTextBox();
		for (CodeSet set : CodeSetManager.instance().sets()) 
			setAdded(set);
		CodeSetManager.instance().addListener(this);
	}

	private void addTextBox() {
//		Text text = new Text(sideBar,SWT.BORDER);
			new TextBox(sideBar);
	}

	Composite view(Composite parent) {
		Composite sideBar = new Composite(parent, SWT.NONE);
		RowLayout layout = new RowLayout(SWT.VERTICAL);
		layout.wrap = true;
		layout.spacing  = 5;
		sideBar.setLayout(layout);
		return sideBar;
	}

	void addLink(final SideBarSection section, final CodeSet set) {
		final CodeSetLabel label = section.addSet(set);
		label.getLink().addHyperlinkListener(new IHyperlinkListener() {
			public void linkActivated(HyperlinkEvent e) {
				CodeSetManager.instance().changeState(set);
			}
			public void linkEntered(HyperlinkEvent e) {
			}
			public void linkExited(HyperlinkEvent e) {
			}
		});
	}
	
	void addLinks(String category, List<CodeSet> sets) {
		SideBarSection section = sections.get(category);
		section.clear();
		for (CodeSet set : sets)
			addLink(section, set);
		sideBar.layout();
	}

	List<CodeSetLabel> labels() {
		ArrayList<CodeSetLabel> links = new ArrayList<CodeSetLabel>();
		for (SideBarSection section : sections.values())
			links.addAll(section.labels());
		return links;
	}
	
	CodeSetLabel findLabel(CodeSet set) {
		for (CodeSetLabel label : labels()) 
			if (label.getSet() == set) return label;
		return null;
	}

	// the following methods are for listening to events generated by the CodeSetManager

	public void setAdded(final CodeSet set) {
		
		Display.getDefault().asyncExec(new Runnable() {
			public void run() {
				if (!sections.containsKey(set.category))
					sections.put(set.category, new SideBarSection(sideBar, set.category));
				addLinks(set.category, CodeSetManager.instance().sets(set.category));
			}
		});
	}
	
	public void setChanged(CodeSet set) {
		CodeSetLabel label = findLabel(set);
		if (label != null) {
			label.setSizeText();
			label.layout();
		}
	}
	public void focusChanged(ISourceReference focus) {
		for (CodeSetLabel label : labels()) {
			if (label.getSet().contains(focus))
				label.emphasizeLink();
			else
				label.demphasizeLink();
		}
		sideBar.layout();
	}
	
	public void stateChanged(CodeSet set) {
		CodeSetLabel label = findLabel(set);
		if (label != null) {
			label.setIcon(set.state);
			label.layout();
		}
	}
	
	public Composite getSideBar() {
		return this.sideBar;
	}
}

